#!/bin/bash
SRC=/home/betaflight/configurator
DST=/home/betaflight/BFAPK

echo "=== 1. capacitor.settings.gradle 수정 (node_modules 경로 -> capacitor-android) ==="
cat > "$DST/capacitor.settings.gradle" << 'EOF'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('./capacitor-android/capacitor')
EOF
cat "$DST/capacitor.settings.gradle"

echo ""
echo "=== 2. 웹앱 빌드 결과 복사 (public/) ==="
rm -rf "$DST/app/src/main/assets/public"
cp -r "$SRC/src/dist" "$DST/app/src/main/assets/public"
echo "웹앱 파일 수: $(find "$DST/app/src/main/assets/public" -type f | wc -l)"
echo "index.html 확인:"
head -3 "$DST/app/src/main/assets/public/index.html"

echo ""
echo "=== 3. 안드로이드 res 파일 복사 ==="
rm -rf "$DST/app/src/main/res"
cp -r "$SRC/android/app/src/main/res" "$DST/app/src/main/res"
echo "res 파일 수: $(find "$DST/app/src/main/res" -type f | wc -l)"
echo "strings.xml 확인:"
cat "$DST/app/src/main/res/values/strings.xml"

echo ""
echo "=== 4. capacitor 설정 파일 복사 ==="
cp "$SRC/capacitor.config.base.json" "$DST/capacitor.config.base.json"
cp "$SRC/capacitor.config.json" "$DST/capacitor.config.json"
echo "capacitor.config.json:"
cat "$DST/capacitor.config.json"

echo ""
echo "=== 5. 안드로이드 assets 설정 복사 ==="
cp "$SRC/android/app/src/main/assets/capacitor.plugins.json" "$DST/app/src/main/assets/capacitor.plugins.json" 2>/dev/null || echo "[]" > "$DST/app/src/main/assets/capacitor.plugins.json"
echo "capacitor.plugins.json:"
cat "$DST/app/src/main/assets/capacitor.plugins.json"

echo ""
echo "=== 6. settings.gradle 확인 ==="
cat "$DST/settings.gradle"

echo ""
echo "=== 7. 빌드 가능 여부 체크 ==="
echo "필요 디렉토리 존재 확인:"
for d in "$DST/app/src/main/java" "$DST/app/src/main/res" "$DST/app/src/main/assets/public" "$DST/capacitor-android" "$DST/capacitor-cordova-android-plugins" "$DST/gradle/wrapper"; do
  if [ -d "$d" ]; then
    echo "  ✓ $d"
  else
    echo "  ✗ $d (MISSING!)"
  fi
done

echo ""
echo "=== 복사 완료 ==="