#!/bin/bash
set -e

BFAPK=/home/betaflight/BFAPK
BACKUP=/home/betaflight/BFAPK_backup
TEMP=/tmp/bf_repo_clone

echo "=== Step 0: 백업 파일 확인 ==="
ls -la $BACKUP/
ls -la ${BACKUP}2/

echo ""
echo "=== Step 1: BFAPK 정리 ==="
rm -rf $BFAPK/*
rm -rf $BFAPK/.git

echo ""
echo "=== Step 2: 원격 저장소에서 전체 프로젝트 클론 ==="
rm -rf $TEMP
git clone https://github.com/saydals/bf.git $TEMP

echo ""
echo "=== Step 3: 전체 프로젝트를 BFAPK로 복사 ==="
cp -r $TEMP/* $BFAPK/
cp -r $TEMP/.git $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.gitignore $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.editorconfig $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.github $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.husky $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.vscode $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.storybook $BFAPK/ 2>/dev/null || true
cp -r $TEMP/.prettier* $BFAPK/ 2>/dev/null || true

echo ""
echo "=== Step 4: BFAPK 전용 Android 설정 적용 ==="
# 4a. capacitor.settings.gradle - node_modules 경로 제거
cat > $BFAPK/capacitor.settings.gradle << 'GRADLE1'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('./capacitor-android/capacitor')
GRADLE1

# 4b. app/build.gradle - release signing 추가
sed -i 's/minifyEnabled false/minifyEnabled false\n            signingConfig signingConfigs.debug/' $BFAPK/android/app/build.gradle

# 4c. package.json - android-only 스크립트 유지
cat > $BFAPK/package.json << 'PKGJSON'
{
  "name": "betaflight-bfapk",
  "version": "2026.6.0-alpha",
  "description": "Betaflight Android App - Complete standalone project (web + Android)",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "android:sync": "vite build && npx cap sync android",
    "android:debug": "vite build && npx cap sync android && cd android && ./gradlew assembleDebug",
    "android:release": "vite build && npx cap sync android && cd android && ./gradlew assembleRelease"
  },
  "repository": { "type": "git", "url": "github.com/saydals/bf" },
  "license": "GPL-3.0"
}
PKGJSON

# 4d. capacitor.config.json webDir을 android 기준으로 유지
echo '{"appId":"betaflight.app","appName":"Betaflight App","webDir":"src/dist"}' > $BFAPK/capacitor.config.json

echo ""
echo "=== Step 5: npm 패키지 설치 ==="
cd $BFAPK
npm install 2>&1 | tail -10

echo ""
echo "=== Step 6: 웹앱 빌드 ==="
cd $BFAPK
npm run build 2>&1 | tail -10

echo ""
echo "=== Step 7: Capacitor sync + Android APK 빌드 ==="
cd $BFAPK
npx cap sync android 2>&1 | tail -10
cd android && ./gradlew assembleDebug 2>&1 | tail -10

echo ""
echo "=== 완료! ==="
ls -lh $BFAPK/android/app/build/outputs/apk/debug/app-debug.apk 2>/dev/null || echo "APK not found"