#!/bin/bash
set -e

BFAPK=/home/betaflight/BFAPK
SRC=/home/betaflight/configurator

echo "=== 1. capacitor-android, capacitor-cordova-android-plugins 복사 ==="
cp -r $SRC/android/capacitor-cordova-android-plugins $BFAPK/
mkdir -p $BFAPK/capacitor-android
cp -r $SRC/node_modules/@capacitor/android/capacitor/* $BFAPK/capacitor-android/ 2>/dev/null
echo "  capacitor-android:" && ls $BFAPK/capacitor-android/ | head -3
echo "  capacitor-cordova:" && ls $BFAPK/capacitor-cordova-android-plugins/ | head -3

echo ""
echo "=== 2. capacitor.settings.gradle 작성 ==="
cat > $BFAPK/capacitor.settings.gradle << 'GRADLE1'
// DO NOT EDIT THIS FILE! IT IS GENERATED EACH TIME "capacitor update" IS RUN
include ':capacitor-android'
project(':capacitor-android').projectDir = new File('./capacitor-android/capacitor')
GRADLE1
cat $BFAPK/capacitor.settings.gradle

echo ""
echo "=== 3. android/settings.gradle 수정 (capacitor.settings 경로 포함 확인) ==="
cat $BFAPK/android/settings.gradle

echo ""
echo "=== 4. app/build.gradle에 release signing 추가 ==="
sed -i 's/minifyEnabled false/minifyEnabled false\n            signingConfig signingConfigs.debug/' $BFAPK/android/app/build.gradle
grep -A2 'release' $BFAPK/android/app/build.gradle

echo ""
echo "=== 5. npm install 시작 ==="
cd $BFAPK && npm install 2>&1 | tail -20

echo ""
echo "=== 6. Vite 빌드 ==="
cd $BFAPK && npm run build 2>&1 | tail -10

echo ""
echo "=== 7. Capacitor sync + APK 빌드 ==="
cd $BFAPK
npx cap sync android 2>&1 | tail -10
cd android && ./gradlew assembleDebug 2>&1 | tail -10

echo ""
echo "=== 완료! ==="
ls -lh $BFAPK/android/app/build/outputs/apk/debug/app-debug.apk 2>/dev/null || echo "APK not found"
ls -lh $BFAPK/app.apk 2>/dev/null && echo "app.apk at root also available" || true